#! /bin/bash
#

api_url="http://127.0.0.1/api_jsonrpc.php"
zbx_imp="python3 /usr/share/doc/ubnt-zabbix-template/import.py"
api_cfg_import="$zbx_imp --url $api_url --user visor --password ping"

rm -f /etc/nginx/sites-enabled/default
rm -f /etc/systemd/system/multi-user.target.wants/zabbix-server.service
awk -F":" '{if ($1=="postgres") system("chown -R " $3":"$4 " /var/lib/postgresql/16/main/") }' /etc/passwd
ln -s /lib/systemd/system/zabbix-server.service /etc/systemd/system/multi-user.target.wants/zabbix-server.service
cp -rf /tmp/etc/ /
cp -rf /tmp/lib/systemd /lib/
cp -rf /tmp/usr/ /
#chown -R postgres:postgres /var/lib/postgresql/
#pg_dropcluster 12 main
#sudo -u postgres dropdb zabbix
#sudo -u postgres dropuser zabbix
#pg_createcluster 16 main
#chown -R postgres.postgres /run/postgresql/
#pg_ctlcluster 16 main start
sudo -u postgres createuser -w zabbix
sudo -u postgres createdb -O zabbix zabbix
echo "ALTER USER zabbix WITH PASSWORD 'netping';" | sudo -u postgres psql zabbix
cat /usr/share/doc/ubnt-zabbix-template/dump.sql.gz | gzip -dc | sudo -u postgres psql -d zabbix

sensors-detect --auto

$api_cfg_import "Zabbix_6.0-6.4.xml"
$api_cfg_import "export_zabbix_server.xml"
$api_cfg_import "zbx_export_internal_netping.xml"
cp /usr/share/doc/ubnt-zabbix-template/sendsms2.sh /usr/lib/zabbix/alertscripts/
$api_cfg_import "mediatype_sms_via_np.xml"

rm -rf /tmp/etc /tmp/lib /tmp/usr

systemctl restart zabbix-server


exit 0
