#! /bin/bash
#

rm -f /etc/nginx/sites-enabled/default
rm -f /etc/systemd/system/multi-user.target.wants/zabbix-server.service
awk -F":" '{if ($1=="postgres") system("chown -R " $3":"$4 " /var/lib/postgresql/16/main/") }' /etc/passwd
ln -s /lib/systemd/system/zabbix-server.service /etc/systemd/system/multi-user.target.wants/zabbix-server.service
cp -rf /tmp/etc/ /
cp -rf /tmp/lib/systemd /lib/
cp -rf /tmp/usr/ /
rm -rf /tmp/etc /tmp/lib /tmp/usr

# echo "*/10 * * * * /usr/share/doc/ubnt-zabbix-template/postinst.sh" >/var/spool/cron/crontabs/root

exit 0
