#!/bin/bash

rm -f /etc/nginx/sites-enabled/default
rm -R /var/lib/postgresql/12/main
rm /etc/systemd/system/multi-user.target.wants/zabbix-server.service
cp -r /tmp/zabbix-ins/etc/* /etc/
cp -r /tmp/zabbix-ins/lib/* /lib/
cp -r /tmp/zabbix-ins/var/* /var/
awk -F":" '{if ($1=="postgres") system("chown -R " $3":"$4 " /var/lib/postgresql/12/main/") }' /etc/passwd
ln -s /lib/systemd/system/zabbix-server.service /etc/systemd/system/multi-user.target.wants/zabbix-server.service
chmod -R u+rw /var/lib/postgresql/12/main/
pg_ctlcluster 12 main start

exit 0
